---
- name: Define Project Root
  ansible.builtin.import_playbook: "../utilities/define_project_root.yaml"
  when: project_root is not defined 

- name: Deploy Container
  hosts: "{{ ('reachable' not in groups and 'unreachable' not in groups) | ternary('all', 'reachable') }}"
  strategy: free
  gather_facts: false
  tasks:
    - name: Deploy Container
      ansible.builtin.include_tasks: execute_deployment.yaml
      with_items: "{{ containers }}"
