version: '3'
services:
  arduino-adapter:
    image: pi-arduino-adapter:latest
    build:
      context: ./arduino-adapter/
      dockerfile: ./Dockerfile
    restart: on-failure
    privileged: true
    network_mode: "host"
    volumes:
      - ./configs:/app/configs