---
assets:
  vars:
    tarfile: arduino.tar
    mqtt_broker: 192.168.1.100
    heater_channel: 1
    light_channel: 2
    serial_port: /dev/ttyACM0
    interface: eth0
    username: ubuntu
    pw: bellavr23
    sync_clocks: true
  hosts:
    ############################################################################################################
    ######################################### R A S P B E R R Y  P I S #########################################
    ############################################################################################################
    A: #Laser building 1
      ansible_host: 192.168.1.162
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    B: #Laser building 1
      ansible_host: 192.168.1.156
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    C: #Laser building 1
      ansible_host: 192.168.1.164
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    D: #Laser building 1
      ansible_host: 192.168.1.165
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    E: #Laser building 1
      ansible_host: 192.168.1.167
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    F: #Laser building 1
      ansible_host: 192.168.1.160
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    G: #Laser building 1
      ansible_host: 192.168.1.161
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    H: #Laser building 1
      ansible_host: 192.168.1.159
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"

    I: #Laser building 1
      ansible_host: 192.168.1.163
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ pw }}"
      ansible_become_password: "{{ ansible_ssh_pass }}"
      data_root: /home/{{ ansible_user }}
      containers:
        - image: "{{ tarfile }}"
